# .dependabot.yml
#
# Setup for dependabot on github
#
# @category  None
# @package   \
# @author    Rick Morice <rick@floor9design.com>
# @copyright Floor9design Ltd
# @license   MIT
# @version   2.0.0
# @link      https://github.com/floor9design-ltd/json-api-formatter
# @link      https://floor9design.com
# @since     File available since pre-release development cycle
version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
